# Generated by Django 5.2.8 on 2025-11-16 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('etiquetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('etiquetas', models.ManyToManyField(blank=True, to='etiquetas.etiqueta')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.prioridad')),
                ('proximidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.proximidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
