# Generated by Django 5.2.8 on 2025-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
