# Generated by Django 5.2.8 on 2025-11-16 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
        ('referencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencias',
            name='precio',
        ),
        migrations.AddField(
            model_name='referencias',
            name='autor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='referencias',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='etiquetas.etiqueta'),
        ),
        migrations.CreateModel(
            name='Pensamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='etiquetas.etiqueta')),
            ],
        ),
    ]
