# Generated by Django 5.2.8 on 2025-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('muy alta', 'muy Alta'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proximidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('corto', 'Corto Plazo'), ('mediano', 'Mediano Plazo'), ('largo', 'Largo Plazo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('rojo', 'Tramite'), ('azul', 'Plan'), ('verde', 'Verde'), ('amarillo', 'Amarillo')], max_length=20)),
            ],
        ),
    ]
