# Generated by Django 5.2.8 on 2025-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_tipo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='color',
            field=models.CharField(choices=[('tramite', 'Tramite'), ('plan', 'Plan'), ('academico', 'academico'), ('amarillo', 'practica')], max_length=20),
        ),
    ]
