# Generated by Django 5.2.8 on 2025-11-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_tipo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='color',
            field=models.CharField(choices=[('rojo', 'Tramite'), ('azul', 'Plan'), ('verde', 'academico'), ('amarillo', 'practica')], max_length=20),
        ),
    ]
